### ISSUE TITLE
How can I solve the OverflowError ?

### ISSUE THREAD

**Issue by xizhesun** [tjs23/nuc_processing#13]
Dear developers,

The command line was as follows:

`nuc_process -cn Chr.name.txt -re1 DpnII  -qm 30 -n 128 -r 3 -o Fol007  -g GENOME_index/Fol007 -pdf report -b /home/data2/mals/anaconda3/envs/nucprocess/bin/bowtie2 -p -v -a -k -sam reads_R?.fastq.gz`

the error message was as follows:

> INFO: Min. contig size not specified, using 10.0% of largest: 550,000 bp
> INFO: Considering 1 chromosomes/contigs
> INFO: Full contact map size 6 x 6
> Traceback (most recent call last):
>   File "/home/data2/mals/anaconda3/envs/nucprocess/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/data2/mals/anaconda3/envs/nucprocess/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/data2/mals/tools/nuc_processing/hic_core/nuc_process.py", line 3808, in <module>
>     main()
>   File "/home/data2/mals/tools/nuc_processing/hic_core/nuc_process.py", line 3787, in main
>     nuc_process(fastq_path_pair, genome_index, genome_index2, re1, re2, c1, c2, sizes, min_rep,
>   File "/home/data2/mals/tools/nuc_processing/hic_core/nuc_process.py", line 3538, in nuc_process
>     contact_map([npz_path], pdf_path, bin_size=None, bin_size2=250.0,
>   File "/home/data2/mals/tools/nuc_processing/nuc_tools/tools/contact_map.py", line 2507, in contact_map
>     plot_contact_matrix(matrix, pair_bin_size, title, scale_label, None, pair,
>   File "/home/data2/mals/tools/nuc_processing/nuc_tools/tools/contact_map.py", line 1357, in plot_contact_matrix
>     tick_delta, nminor = _get_tick_delta(b, bin_size/unit)
>   File "/home/data2/mals/tools/nuc_processing/nuc_tools/tools/contact_map.py", line 823, in _get_tick_delta
>     sf = int(floor(np.log10(tick_delta_units)))
> OverflowError: cannot convert float infinity to integer

**Comment by tjs23** [comment]
I can see why this happens; the bin size used in the contact map doesn't adapt to smaller chromosome/region sizes. Instigating a fix now...
T.

**Comment by xizhesun** [comment]
Hi T,

Yeah, you are right.  It's a fungi genome. Several small Chromosomes were in the genome data. Look forward to your fixing this bug. Many thanks!

Best regards,
Xizhe

**Comment by tjs23** [comment]
Hi Xizhe,
This should be fixed now, as I added auto-scaling to the contact map. I didn't notice the issue before as we mostly work with mammalian data. Note that most of the changes are in the nuc_tools sub-module (links a separate repo. which is also updated). Let me know of any further problems...
Best,
T.

**Comment by xizhesun** [comment]
Hi T,

I will test it soon. Thank you!

All best,
Xizhe
