### ISSUE TITLE
confused with"The number of the ambiguity group to which the paired reads belong"

### ISSUE THREAD

**Issue by ivyhzau** [tjs23/nuc_processing#2]
The format of my interaction data is hic file. I am confused with"The number of the ambiguity group to which the paired reads belong". How to calculate the number. Can I get the nunber from my hic file.
Looking forward for your help.

**Comment by tjs23** [comment]
The ambiguity group number simply links contacts representing different alternative sequence mappings, i.e. grouped contacts share the same group number. Hi-C data will often not have ambiguity information, as such sequence mappings are usually discarded. In this case the ambiguity groups can be set to sequential integers (i.e. number the rows), so you get a different value for each contact. For info, though the Aiden .hic format is not currently supported this may be added in the future.
