### ISSUE TITLE
Getting contact map for individual chromosomes?

### ISSUE THREAD

**Issue by tarak77** [tjs23/nuc_processing#5]
Hi Tim,

Currently the contact_map.svg file shows all chromosomes for a cell. Is it possible to obtain the contact matrix for individual chromosomes in .npy or related formats? using nuc_contact_map function?

Thanks,
Tarak

**Comment by tjs23** [comment]
No, but a binned .npz based format will eventually appear in nuc_processing. However, this is currently only available in nuc_tools [https://github.com/lmb-seq/nuc_tools/], which is somewhat work-in-progress. Nonetheless, here you can use `./nuc_tools  ncc_bin` to convert .ncc files to a NumPy archive (savez_compressed). This uses SciPy sparse matrices and variable unsigned integer sizes to get fairly efficient storage for bulk Hi-C data.
