### ISSUE TITLE
TypeError when creating restriction enzyme fragment file

### ISSUE THREAD

**Issue by Christian-Heyer** [tjs23/nuc_processing#7]
Using the release_1.0 branch: when I attempt to run nuc_process and create the restriction enzyme track, it fails with the following error
```
 INFO : Creating restriction enzyme fragment file /path/to/bowtieindex/RE_frag_MboI_GCA_000001405.15_GRCh38_no_alt_analysis_set.txt
    INFO : Calculating MboI fragment locations for chr10 contig chr10
Traceback (most recent call last):
  File "/path/to/.conda/envs/nuc_process/bin/nuc_process", line 11, in <module>
    sys.exit(main())
  File "/path/to/.conda/envs/nuc_process/lib/python3.6/site-packages/nuc_processing/NucProcess.py", line 2866, in main
    lig_junc, zip_files, sam_format, verbose)
  File "/path/to/.conda/envs/nuc_process/lib/python3.6/site-packages/nuc_processing/NucProcess.py", line 2581, in nuc_process
    re1_files = [check_re_frag_file(genome_index, re1, g_fastas, align_exe, num_cpu, remap=remap)]
  File "/path/to/.conda/envs/nuc_process/lib/python3.6/site-packages/nuc_processing/NucProcess.py", line 1594, in check_re_frag_file
    frag_data[contig] = get_chromo_re_fragments(fasta_file_objs, contig, seq.upper(), re_site, cut_pos)
  File "/path/to/.conda/envs/nuc_process/lib/python3.6/site-packages/nuc_processing/NucProcess.py", line 1454, in get_chromo_re_fragments
    sub_seq = frag_seq[a:b]
TypeError: slice indices must be integers or None or have an __index__ method
```

This happend using different assembly fasta files so I took a look at the NucProcess.py and saw that the a and b variables at line 1454 function seem to take on non-integer values. I was able to get NucProcess to run by modifying line 1434 in the NucProcessfile to `step = int(mappability_length/2)`, forcing `step` to be rounded in case it takes on a non-integer value.
 
With this change nuc_process produces results, however I am unsure if this may cause any unwanted effects down the line. While I didn't see how this would be influenced by my input files for how I call the nucProcess function, I may be missing something. 
For completeness sake I have added my nuc_process function call. 
```
nuc_process -f /path/to/fastas/grch38_fastas/*.fa -o sample1 -v -a -k -re1 MboI -s 150-2000 -n 4 -g /path/to/bowtieindex/GCA_000001405.15_GRCh38_no_alt_analysis_set -i /path/to/fastq1 /path/to/fastq2
```

**Comment by tjs23** [comment]
Thanks, this seems to be an appropriate fix and shouldn't cause any problems. I have changed release_1.0 accordingly. Note that in the master branch the handling of mappability has changed so this issue doesn't apply there.
