### ISSUE TITLE
Parameter for data without restriction site (e.g. DNase type)

### ISSUE THREAD

**Issue by gundalav** [tjs23/nuc_processing#8]
I'm currently working with single-cell data with DNAse type.
Which doesn't contain restriction enzyme.
Is there a way to run `nuc_process` with that data?
Perhaps a specific way to annotate the `enzymes.conf` file?

Thanks and hope to hear from you again. 
G.V.

**Comment by tjs23** [comment]
Unfortunately the part of the code which handles the filtering of paired reads would need to be adjusted to handle this properly. I suspect that putting in a fake RE1 site that cuts very often would cause problems. However, you may get an acceptable result by running `nuc_process` with several different RE1 values, each using a different 4-base recognition site, and then merging and de-duplicating the results afterwards; removing pairs with overlapping reads at both ends. - You want the union of runs with no filtering based on RE1 fragment. Also the output .ncc file, which normally contains the downstream RE1 position, should be adjusted to have the RE1 position set to some standard offset relative to the reads.

**Comment by tjs23** [comment]
Version 1.3 (master branch) now properly supports non-RE based protocols like Micro-C; set `-re1 None`. When using this option the filtering of read pairs is necessarily much simpler than with RE sites, hence many of the quality controls, and associated reports, will not be present.
